name: Mirror
on:
  push:
    branches:
      - main
jobs:
  to-gitee:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror to Gitee
      uses: wei/git-sync@v3
      with:
        source_repo: "sabersalv/awesome-pt"
        source_branch: "main"
        destination_repo: "git@gitee.com:sabersalv/awesome-pt.git"
        destination_branch: "main"
        destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} 


